server:
  port: 8081

spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/parkingdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:parking_user}
    password: ${DB_PASSWORD:parking_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

logging:
  level:
    org.example.parking: DEBUG

