server:
  port: 8083

spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:h2:mem:reservationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      parking-service:
        connectTimeout: 3000
        readTimeout: 10000
      vehicle-service:
        connectTimeout: 3000
        readTimeout: 10000

logging:
  level:
    org.example.reservation: DEBUG
    org.example.reservation.client: DEBUG

