server:
  port: 8083

spring:
  application:
    name: reservation-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/reservationdb
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:reservation_user}
    password: ${DB_PASSWORD:reservation_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9000}

logging:
  level:
    org.example.reservation: DEBUG
    org.example.reservation.client: DEBUG

