# Универсальный простой Dockerfile для уже собранных JAR файлов
ARG SERVICE_NAME
FROM --platform=linux/amd64 eclipse-temurin:17-jre

WORKDIR /app

# Копируем готовый JAR файл
ARG SERVICE_NAME
COPY ${SERVICE_NAME}/target/*.jar app.jar

# Запускаем приложение
ENTRYPOINT ["java", "-jar", "app.jar"]

